version: "3.8"
services:
  elastic:
    image: elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - path.data=/usr/share/elasticsearch/data
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.13.0
    environment:
      - path.data=/usr/share/kibana/data
      - elasticsearch.hosts=["http://elastic:9200"]
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"

volumes:
  elastic-data:
  kibana-data:
