apiVersion: v1
kind: Service
metadata:
  labels:
    app: cinema-seek-api
  name: cinema-seek-api
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: "api"
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: cinema-seek-api
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: cinema-seek-elastic
  name: elastic
spec:
  ipFamilies:
    - IPv4
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: cinema-seek-elastic
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: cinema-seek-redis
  name: redis
spec:
  ipFamilies:
    - IPv4
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: cinema-seek-redis
  type: ClusterIP
